notifications:
  email:
    - nuxseme@gmail.com
  on_success: always
  on_failure: always

script:
  - ssh -V
addons:
  ssh_known_hosts: ${SERVER_HOST}

after_success:
  - ssh ${USERNAME}@${SERVER_HOST} -p ${PASSWORD} 'ls'

