language: generic
notifications:
  email:
  - nuxseme@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts:
    - 47.88.8.216
before_install:
   - echo -e "Host 47.88.8.216\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
   - openssl aes-256-cbc -K $encrypted_a6b36f5c33c8_key -iv $encrypted_a6b36f5c33c8_iv
     -in deploy_key.enc -out ~/.ssh/id_rsa -d
   - chmod 600 ~/.ssh/id_rsa

after_success:
  - cat ~/.ssh/known_hosts
  - cat ~/.ssh/config
  - ls ~/.ssh/
  - ssh ${USERNAME}@${SERVER_HOST} -vv

