 notifications:
  email:
  - nuxseme@gmail.com
  on_success: always
  on_failure: always
 before_install:
   - openssl aes-256-cbc -K $encrypted_a6b36f5c33c8_key -iv $encrypted_a6b36f5c33c8_iv
     -in deploy_key.enc -out /temp/deploy -d
   - eval "$(ssh-agent -s)"
   - chmod 600 /tmp/deploy
   - ssh-add /tmp/deploy

addons:
  ssh_known_hosts: "${SERVER_HOST}"
after_success:
  - ssh ${USERNAME}@${SERVER_HOST} 'ls'

