language: generic
notifications:
  email:
  - nuxseme@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts:
    - ${SERVER_HOST}
before_install:
   - echo -e "Host ${SERVER_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
   - openssl aes-256-cbc -K $encrypted_a6b36f5c33c8_key -iv $encrypted_a6b36f5c33c8_iv
     -in deploy_key.enc -out ~/.ssh/deploy_key -d

after_success:
  - cat $HOME/.ssh/known_hosts
  - cat ~/.ssh/config
  - ssh ${USERNAME}@${SERVER_HOST} 'ls'

