language: generic
notifications:
  email:
  - nuxseme@gmail.com
  on_success: always
  on_failure: always
before_install:
   - echo -e "Host ${SERVER_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
   - openssl aes-256-cbc -K $encrypted_a6b36f5c33c8_key -iv $encrypted_a6b36f5c33c8_iv
     -in deploy_key.enc -out ~/.ssh/id_rsa -d
   - chmod 600 ~/.ssh/id_rsa

after_success:
  - ssh ${USERNAME}@${SERVER_HOST} < deploy.sh

